version: 0.2

env:
  variables:
    DB_HOST: "your-remote-db-host"
    DB_NAME: "your-database-name"
    DB_USER: "your-database-user"
    DB_PASSWORD: "your-database-password"
    S3_BUCKET: "my-test-bucket-southeast-2"

phases:
  pre_build:
    commands:
      - echo "Logging into Docker..."
      - docker pull registry.gitlab.com/dalibo/postgresql_anonymizer:latest
      - echo "Docker image pulled successfully."

      - echo "Starting PostgreSQL container..."
      - docker run -d --name pg_container -e POSTGRES_PASSWORD=${DB_PASSWORD} registry.gitlab.com/dalibo/postgresql_anonymizer:latest
      - echo "PostgreSQL container started successfully."

      - echo "Downloading anonymization rules..."
      - aws s3 cp s3://my-test-bucket-southeast-2/sqlFiles/sinorbis/config/rules.sql ./rules.sql
      - echo "Files downloaded:"
      - ls -la

  build:
    commands:
      - echo "Connecting to the remote PostgreSQL instance and running test query..."
      - export PGPASSWORD=${DB_PASSWORD}
      - docker run -v $(pwd):/workspace registry.gitlab.com/dalibo/postgresql_anonymizer:latest sh -c "PGPASSWORD=${DB_PASSWORD} pg_dump -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} | cat - /workspace/rules.sql | /src/docker/anon.sh > /workspace/anonymized.sql"
      - echo "Query output saved to query_output.txt"
      - cat anonymized.sql

  post_build:
    commands:
      - echo "Build script completed."

artifacts:
  files:
    - rules.sql
