version: 0.2

env:
  variables:
    DB_HOST: "52.64.11.246"
    DB_NAME: "irvdblive"
    DB_USER: "irvuser"
    DB_PASSWORD: "irvpass"
    S3_BUCKET: "my-test-bucket-southeast-2"

phases:
  pre_build:
    commands:
      - echo "Logging into Docker..."
      - docker pull registry.gitlab.com/dalibo/postgresql_anonymizer:latest
      - echo "Docker image pulled successfully."
      - echo "Downloading JAR file from S3..."
      - aws s3 cp s3://$S3_BUCKET/sqlFiles/sinorbis/config/pgsql.jar ./pgsql.jar
      - aws s3 cp s3://$S3_BUCKET/sqlFiles/sinorbis/config/rules.sql ./rules.sql
      - echo "JAR file downloaded."

  build:
    commands:
      - echo "Dumping database schema only..."
      - docker run --rm --network="host" -v $(pwd):/workspace registry.gitlab.com/dalibo/postgresql_anonymizer:latest sh -c "PGPASSWORD=$DB_PASSWORD pg_dump --schema-only -h $DB_HOST -p 5432 -U $DB_USER -d $DB_NAME > /workspace/test_db.sql"
      - echo "Database schema dump complete."
      
      - echo "Running the JAR file with Java 17 and passing environment variables..."
      # Replace the placeholders with the environment variables and pass them to the JAR
      - java -jar pgsql.jar --conf.path=$(pwd)/test_db.sql --spring.datasource.url=jdbc:postgresql://$DB_HOST:5432/$DB_NAME --spring.datasource.username=$DB_USER --spring.datasource.password=$DB_PASSWORD
      - echo "JAR execution complete."

      - docker run -v $(pwd):/workspace registry.gitlab.com/dalibo/postgresql_anonymizer:latest sh -c "cat /workspace/test_db.sql /workspace/rules.sql | /src/docker/anon.sh > /workspace/anonymized.sql"

  post_build:
    commands:
      - echo "Displaying the contents of the dump file..."
      - cat test_db.sql
      - echo "Build complete."
      - ls -la

artifacts:
  files:
    - test_db.sql
