version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Docker..."
      - docker pull registry.gitlab.com/dalibo/postgresql_anonymizer:stable
      - echo "Docker image pulled successfully."
      
      - echo "Creating backup of the database..."
      - docker run --rm \
          -e PGPASSWORD=irvpass \
          -v $(pwd):/workspace \
          postgres:latest \
          pg_dump -h 52.64.11.237 -U irvuser -d irvdblive -f /workspace/test_db.sql
          
      - echo "Backup created successfully."
      - echo "Downloading anonymization rules..."
      - aws s3 cp s3://my-test-bucket-southeast-2/sqlFiles/sinorbis/config/rules.sql ./rules.sql
      - echo "Files downloaded:"
      - ls -la

  build:
    commands:
      - echo "Running anonymization"
      - docker run -v $(pwd):/workspace registry.gitlab.com/dalibo/postgresql_anonymizer:stable sh -c "cat /workspace/test_db.sql /workspace/rules.sql | /src/docker/anon.sh > /workspace/anonymized.sql"
      - echo "Anonymization complete"

  post_build:
    commands:
      - echo "Uploading anonymized file to S3"
      - aws s3 cp anonymized.sql s3://my-test-bucket-southeast-2/sqlFiles/sinorbis/anonymizerFiles/anonymized.sql
      - echo "Build complete"
      - ls -la
      - cat anonymized.sql

artifacts:
  files:
    - anonymized.sql
