version: 0.2

env:
  variables:
    DB_HOST: "52.64.11.246"
    DB_NAME: "irvdblive"
    DB_USER: "irvuser"
    DB_PASSWORD: "irvpass"
    S3_BUCKET: "my-test-bucket-southeast-2"

phases:
  pre_build:
    commands:
      - echo "Logging into Docker..."
      - docker pull postgres:latest
      - echo "Docker image pulled successfully."

  build:
    commands:
      - echo "Dumping database..."
      # Using environment variables for database connection
      - docker run --rm --network="host" -v $(pwd):/workspace postgres:latest sh -c "PGPASSWORD=$DB_PASSWORD pg_dump -h $DB_HOST -p 5432 -U $DB_USER -d $DB_NAME -F p > /workspace/test_db.sql"
      - echo "Database dump complete."

  post_build:
    commands:
      - echo "Build complete. The database dump is stored at test_db.sql."
      - ls -la
      - cat test_db.sql

artifacts:
  files:
    - test_db.sql
