version: 0.2

env:
  variables:
    DB_HOST: "52.64.11.246"
    DB_NAME: "irvdblive"
    DB_USER: "irvuser"
    DB_PASSWORD: "irvpass"
    S3_BUCKET: "my-test-bucket-southeast-2"

phases:
  pre_build:
    commands:
      - echo "Logging into Docker..."
      - docker pull registry.gitlab.com/dalibo/postgresql_anonymizer:latest
      - echo "PostgreSQL Anonymizer Docker image pulled successfully."
      - echo "Downloading JAR file and rule file from S3..."
      - aws s3 cp s3://$S3_BUCKET/sqlFiles/sinorbis/config/pgsql.jar ./pgsql.jar
      - aws s3 cp s3://$S3_BUCKET/sqlFiles/sinorbis/config/rules.sql ./rules.sql
      - echo "JAR and rule files downloaded."

  build:
    commands:
      - echo "Dumping database schema only..."
      - docker run --rm --network="host" -v $(pwd):/workspace registry.gitlab.com/dalibo/postgresql_anonymizer:latest sh -c "PGPASSWORD=$DB_PASSWORD pg_dump --schema-only -h $DB_HOST -p 5432 -U $DB_USER -d $DB_NAME > /workspace/test_db.sql"
      - echo "Database schema dump complete."
	  - ls -la
      
      - echo "Verifying existence and contents of test_db.sql and rules.sql files..."
      - cat /workspace/test_db.sql
      - cat /workspace/rules.sql
      - echo "Files verified."


  post_build:
    commands:
      - echo "Uploading anonymized file to S3..."


artifacts:
  files:
    - /workspace/anonymized.sql
